# Generated by Django 5.1.4 on 2024-12-05 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_pedido', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('PENDENTE', 'PENDENTE'), ('ENVIADO', 'ENVIADO'), ('CONCLUIDO', 'CONCLUIDO'), ('CANCELADO', 'CANCELADO')], default='PENDENTE', max_length=100)),
            ],
        ),
    ]
